/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    3: typeof import('./src/components/HomeContent/3.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ArticlePage: typeof import('./src/components/ArticlePage.vue')['default']
    BackHeader: typeof import('./src/components/BackHeader.vue')['default']
    HomeContent1: typeof import('./src/components/HomeContent/HomeContent1.vue')['default']
    HomeContent2: typeof import('./src/components/HomeContent/HomeContent2.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test3: typeof import('./src/components/HomeContent/test3.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheTabbar: typeof import('./src/components/TheTabbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
